### ISSUE TITLE
Issue with viewer

### ISSUE THREAD

**Issue by marco91sol** [blobtoolkit/viewer#52]
Dear all, 

I activate my btk_env environment, where I have the following version of nodejs-> 14.14.0

Then I launch the command:
blobtools view folder_with_different_json_files 

I receive the following output:

Initializing viewer
Traceback (most recent call last):
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 300, in static_view
    driver, display = firefox_driver(args)
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 212, in firefox_driver
    driver = webdriver.Firefox(
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 192, in __init__
    self.service.start()
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 495, in cli
    main(args)
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 480, in main
    static_view(args, loc, viewer)
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/view.py", line 302, in static_view
    format_exc(err)
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/mnt/DATA/home/marcos/anaconda3/envs/snakemake/envs/btk_env/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'WebDriverException' and 'int'

How can I solve that?

**Comment by sujaikumar** [comment]
Responded at https://github.com/blobtoolkit/blobtoolkit/issues/169
